<?php
bolt_decrypt( __FILE__ , 'go5hSq'); return 0;
##!!!##QUGlmKScqqeYmpxXeKenk4Smm5yjqnJBQayqnFeAo6OspKClmKuck3uYq5iZmKqck3yjpqisnKWrk32YmqumqaCcqpN/mKp9mJqrpqmwckGsqpxXgKOjrKSgpZirnJN7mKuYmZiqnJN8o6aorJylq5OEppuco3JBQZqjmKqqV4uco5yeqZikV5yvq5ylm6pXhKabnKNBskFXV1dXrKqcV3+Yqn2YmqumqbByQbRB