<?php
bolt_decrypt( __FILE__ , 'yd8R4b'); return 0;
##!!!##BwdrXmpicG1eYGIdPm1tWUpsYWJpcDgHB3JwYh1GaWlyamZrXnFiWUFecV5fXnBiWUJpbG5yYmtxWUNeYHFsb2ZicFlFXnBDXmBxbG92OAdycGIdRmlpcmpma15xYllBXnFeX15wYllCaWxucmJrcVlKbGFiaTgHB2BpXnBwHVFicHE+YGBscmtxSmJrch1idXFia2FwHUpsYWJpB3gHHR0dHXJwYh1FXnBDXmBxbG92OAd6Bw==